import fire from './fire.png'
import water from './water.png'
import grass from './grass.png'
import electric from './electric.png'
import normal from './normal.png'
import flying from './flying.png'
import poison from './poison.png'
import ground from './ground.png'
import fighting from './fighting.png'
import rock from './rock.png'
import ghost from './ghost.png'
import ice from './ice.png'
import bug from './bug.png'
import dragon from './dragon.png'
import dark from './dark.png'
import steel from './steel.png'
import fairy from './fairy.png'
export { fire }
export { water }
export { grass }
export { electric }
export { normal }
export { flying }
export { poison }
export { ground }
export { fighting }
export { rock }
export { ghost }
export { ice }
export { bug }
export { dragon }
export { dark }
export { steel }
export { fairy }